manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: simtind
      url-base: https://github.com/simtind
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    # - name: zephyr
    #   repo-path: sdk-zephyr
    #   remote: simtind
    #   revision: simtind/ncs+zmk-fixes
    #   clone-depth: 1
    #   import:
    #     # TODO: Rename once upstream offers option like `exclude` or `denylist`
    #     name-blocklist:
    #       - ci-tools
    #       - hal_altera
    #       - hal_cypress
    #       - hal_infineon
    #       - hal_microchip
    #       - hal_nxp
    #       - hal_openisa
    #       - hal_silabs
    #       - hal_xtensa
    #       - hal_st
    #       - hal_ti
    #       - loramac-node
    #       - net-tools
    #       - edtt
    #       - trusted-firmware-m
    #       - sof
    #       - mcuboot
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: main
      import: true
    - name: zmk
      remote: simtind
      revision: simtind/blaatind-fixes
      import: app/west.yml
  self:
    path: zmk/app