on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/build_image.yml
    with:
      build_matrix_path: config/build.yaml
      config_path: config
      extra_cmake_args: -DBOARD_ROOT=\"${GITHUB_WORKSPACE}\"
      fallback_binary: hex
      output_name: merged